# This file is only used by the Devcontainer
# https://www.home-assistant.io/integrations/default_config/
default_config:

# This will let us test energy meters:
utility_meter:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    # Enable debug logging for our custom components
    custom_components.hilo: debug
    pyhilo: debug

# https://www.home-assistant.io/integrations/debugpy/
debugpy:
